AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minecraft Paper Server with BedrockConnect on EC2 using Docker'

Mappings:
  InstanceArchitecture:
    t4g.small:
      Architecture: arm64
    t4g.medium:
      Architecture: arm64
    t4g.large:
      Architecture: arm64
    t3.small:
      Architecture: x86_64
    t3.medium:
      Architecture: x86_64
    t2.small:
      Architecture: x86_64

Parameters:
  InstanceType:
    Description: 'EC2 Instance type'
    Type: String
    Default: t4g.medium
    AllowedValues:
      - t2.small
      - t4g.small
      - t4g.medium
      - t3.small
      - t3.medium
    ConstraintDescription: 'Must be a valid EC2 instance type'

  KeyName:
    Description: 'Name of existing EC2 KeyPair for SSH access'
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: 'Must be the name of an existing EC2 KeyPair'

  SSHLocation:
    Description: 'IP address range that can SSH to the EC2 instance'
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    ConstraintDescription: 'Must be a valid IP CIDR range'

  LatestARM64AmiId:
    Description: 'Latest Amazon Linux 2023 ARM64 AMI ID'
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64'

  LatestX86AmiId:
    Description: 'Latest Amazon Linux 2023 x86_64 AMI ID'
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64'

Conditions:
  IsARM64Instance: !Equals 
    - !FindInMap [InstanceArchitecture, !Ref InstanceType, Architecture]
    - arm64

Resources:
  # VPC Configuration
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-VPC'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-IGW'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Public-Subnet'

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Public-Routes'

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet

  # Security Group Configuration
  MinecraftSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName}-Minecraft-SG'
      GroupDescription: 'Security group for Minecraft server'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        # SSH Access - Restricted to specific IP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation
          Description: 'SSH access from trusted IP only'
        # DNS (TCP) - Required for BedrockConnect to redirect Nintendo Switch
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
          Description: 'DNS TCP - BedrockConnect for Nintendo Switch'
        # DNS (UDP) - Required for BedrockConnect to redirect Nintendo Switch
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
          Description: 'DNS UDP - BedrockConnect for Nintendo Switch'
        # Minecraft Java Edition
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0
          Description: 'Minecraft Java Edition'
        # Minecraft Bedrock Edition (UDP) - Combined port range
        - IpProtocol: udp
          FromPort: 19132
          ToPort: 19133
          CidrIp: 0.0.0.0/0
          Description: 'Minecraft Bedrock/Geyser UDP'
      SecurityGroupEgress:
        # DNS resolution
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
          Description: 'DNS resolution TCP'
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
          Description: 'DNS resolution UDP'
        # HTTP for package downloads
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: 'HTTP for package downloads'
        # HTTPS for secure downloads
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: 'HTTPS for secure downloads'
        # NTP for time sync
        - IpProtocol: udp
          FromPort: 123
          ToPort: 123
          CidrIp: 0.0.0.0/0
          Description: 'NTP time synchronization'
        # Minecraft server list ping
        - IpProtocol: tcp
          FromPort: 25565
          ToPort: 25565
          CidrIp: 0.0.0.0/0
          Description: 'Minecraft server list communication'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Minecraft-SG'

  # S3 Bucket for Minecraft World Backups
  MinecraftBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-minecraft-backups-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldBackups
            Status: Enabled
            ExpirationInDays: 30
            NoncurrentVersionExpirationInDays: 7
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Minecraft-Backups'

  # IAM Role for EC2
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-EC2-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: MinecraftBackupPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt MinecraftBackupBucket.Arn
                  - !Sub '${MinecraftBackupBucket.Arn}/*'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-EC2-Role'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-EC2-InstanceProfile'
      Path: '/'
      Roles:
        - !Ref EC2Role

  # EC2 Instance
  MinecraftInstance:
    Type: AWS::EC2::Instance
    DependsOn: InternetGatewayAttachment
    Properties:
      ImageId: !If 
        - IsARM64Instance
        - !Ref LatestARM64AmiId
        - !Ref LatestX86AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref MinecraftSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            VolumeSize: 20
            DeleteOnTermination: true
            Encrypted: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          
          # Install basic dependencies
          dnf install -y aws-cfn-bootstrap amazon-cloudwatch-agent
          
          # Configure CloudWatch agent
          cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<'EOF'
          {
            "agent": {
              "metrics_collection_interval": 60,
              "run_as_user": "cwagent"
            },
            "metrics": {
              "namespace": "MinecraftServer",
              "metrics_collected": {
                "cpu": {
                  "measurement": [
                    {"name": "cpu_usage_idle", "rename": "CPU_USAGE_IDLE", "unit": "Percent"},
                    {"name": "cpu_usage_iowait", "rename": "CPU_USAGE_IOWAIT", "unit": "Percent"},
                    {"name": "cpu_usage_active", "rename": "CPU_USAGE_ACTIVE", "unit": "Percent"}
                  ],
                  "totalcpu": false,
                  "metrics_collection_interval": 60
                },
                "disk": {
                  "measurement": [
                    {"name": "used_percent", "rename": "DISK_USED_PERCENT", "unit": "Percent"},
                    {"name": "free", "rename": "DISK_FREE", "unit": "Gigabytes"}
                  ],
                  "metrics_collection_interval": 60,
                  "resources": ["*"]
                },
                "mem": {
                  "measurement": [
                    {"name": "mem_used_percent", "rename": "MEM_USED_PERCENT", "unit": "Percent"},
                    {"name": "mem_available", "rename": "MEM_AVAILABLE", "unit": "Megabytes"}
                  ],
                  "metrics_collection_interval": 60
                },
                "netstat": {
                  "measurement": [
                    {"name": "tcp_established", "rename": "TCP_ESTABLISHED", "unit": "Count"},
                    {"name": "tcp_time_wait", "rename": "TCP_TIME_WAIT", "unit": "Count"}
                  ],
                  "metrics_collection_interval": 60
                }
              }
            },
            "logs": {
              "logs_collected": {
                "files": {
                  "collect_list": [
                    {
                      "file_path": "/opt/minecraft/logs/latest.log",
                      "log_group_name": "/aws/ec2/minecraft",
                      "log_stream_name": "{instance_id}/minecraft-server",
                      "retention_in_days": 7
                    },
                    {
                      "file_path": "/var/log/messages",
                      "log_group_name": "/aws/ec2/minecraft",
                      "log_stream_name": "{instance_id}/system",
                      "retention_in_days": 7
                    }
                  ]
                }
              }
            }
          }
          EOF
          
          # Start CloudWatch agent
          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
            -a fetch-config \
            -m ec2 \
            -s \
            -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
          
          # Signal that basic infrastructure is ready
          cfn-signal -e $? --stack ${AWS::StackName} --resource MinecraftInstance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Minecraft-Server'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M

  # Elastic IP for consistent access
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-EIP'

  # Elastic IP Association
  ElasticIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MinecraftInstance
      EIP: !Ref ElasticIP

  # CloudWatch Log Group
  MinecraftLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ec2/minecraft
      RetentionInDays: 7

  # CloudWatch Dashboard
  MinecraftDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${AWS::StackName}-Minecraft-Dashboard'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "MinecraftServer", "CPU_USAGE_ACTIVE", { "stat": "Average" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "CPU Usage",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "MinecraftServer", "MEM_USED_PERCENT", { "stat": "Average" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Memory Usage",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "MinecraftServer", "DISK_USED_PERCENT", { "stat": "Average" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Disk Usage",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "MinecraftServer", "TCP_ESTABLISHED", { "stat": "Average" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Active Connections",
                "period": 300
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 12,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/ec2/minecraft' | fields @timestamp, @message | filter @stream like 'minecraft-server' | sort @timestamp desc | limit 20",
                "region": "${AWS::Region}",
                "title": "Recent Minecraft Server Logs",
                "queryType": "Logs"
              }
            }
          ]
        }

  # SNS Topic for Alerts
  MinecraftAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-Minecraft-Alerts'
      DisplayName: 'Minecraft Server Alerts'

  # CloudWatch Alarms
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-HighCPU'
      AlarmDescription: 'Minecraft server CPU usage is too high'
      MetricName: CPU_USAGE_ACTIVE
      Namespace: MinecraftServer
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref MinecraftAlertTopic
      TreatMissingData: notBreaching

  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-HighMemory'
      AlarmDescription: 'Minecraft server memory usage is too high'
      MetricName: MEM_USED_PERCENT
      Namespace: MinecraftServer
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 85
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref MinecraftAlertTopic
      TreatMissingData: notBreaching

  HighDiskUsageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-HighDiskUsage'
      AlarmDescription: 'Minecraft server disk usage is too high'
      MetricName: DISK_USED_PERCENT
      Namespace: MinecraftServer
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 90
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref MinecraftAlertTopic
      TreatMissingData: notBreaching

  # Instance Status Check Alarm
  InstanceStatusCheckAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-InstanceStatusCheck'
      AlarmDescription: 'Instance has failed status checks'
      MetricName: StatusCheckFailed
      Namespace: AWS/EC2
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: InstanceId
          Value: !Ref MinecraftInstance
      AlarmActions:
        - !Ref MinecraftAlertTopic
      TreatMissingData: breaching

Outputs:
  InstanceId:
    Description: 'EC2 Instance ID'
    Value: !Ref MinecraftInstance

  PublicIP:
    Description: 'Public IP address of the server'
    Value: !Ref ElasticIP

  SSHCommand:
    Description: 'SSH command to connect to the instance'
    Value: !Sub 'ssh -i ${KeyName}.pem ec2-user@${ElasticIP}'

  MinecraftJavaConnection:
    Description: 'Minecraft Java Edition connection address'
    Value: !Sub '${ElasticIP}:25565'

  MinecraftBedrockConnection:
    Description: 'Minecraft Bedrock Edition connection address'
    Value: !Sub '${ElasticIP}:19132'

  BedrockConnectDNS:
    Description: 'DNS server to configure on Nintendo Switch'
    Value: !Ref ElasticIP

  BackupBucket:
    Description: 'S3 bucket for Minecraft world backups'
    Value: !Ref MinecraftBackupBucket

  CloudWatchDashboard:
    Description: 'CloudWatch Dashboard URL'
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${AWS::StackName}-Minecraft-Dashboard'

  SNSAlertTopic:
    Description: 'SNS Topic for server alerts (subscribe to receive notifications)'
    Value: !Ref MinecraftAlertTopic